server:
  port: 9099

spring:
  application:
    name: analytics-service

# Eureka Registration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Monitoring and Refreshing
management:
  endpoints:
    web:
      exposure:
        include: "health,info,refresh"
  endpoint:
    health:
      show-details: always

# Swagger Documentation 
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
