server:
  port: 9100
# Eureka Registration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
# Inside your Config Server Repo
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/audit_db?createDatabaseIfNotExist=true
    username: root
    password: admin@123
  jpa:
    hibernate:
      ddl-auto: update
# Management endpoints for monitoring (Actuator)
management:
  endpoints:
    web:
      exposure:
        include: "health,info,refresh"
  endpoint:
    health:
      show-details: always

