server:
  port: 9090

spring:
  application:
    name: identity-service

  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/identity_db?createDatabaseIfNotExist=true
    username: root
    password: admin@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false



# Eureka Registration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Management endpoints for monitoring (Actuator)
management:
  endpoints:
    web:
      exposure:
        include: "health,info,refresh"
  endpoint:
    health:
      show-details: always

# JWT & Auth Properties
jwt:
  secret: mysecretmysecretmysecretmysecret
  expiration: 900000        # 15 Minutes
  refresh:
    expiration: 604800000   # 7 Days

app:
  password_reset_url: "http://localhost:9090/reset-password?token={token}"

# Swagger Documentation 
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
