package com.cts.fundtrack.disbursement.service;

import java.time.Instant;
import java.time.LocalDate;
import java.util.Collections;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.cts.fundtrack.common.aspect.Auditable;
import com.cts.fundtrack.common.client.NotificationClient;
import com.cts.fundtrack.common.dto.NotificationRequestDTO;
import com.cts.fundtrack.common.dto.PaymentRequestDTO;
import com.cts.fundtrack.common.dto.PaymentResponseDTO;
import com.cts.fundtrack.common.exceptions.DisbursementNotFoundException;
import com.cts.fundtrack.common.exceptions.DuplicateTransactionException;
import com.cts.fundtrack.common.exceptions.InvalidProgramStateException;
import com.cts.fundtrack.common.exceptions.PaymentNotFoundException;
import com.cts.fundtrack.common.models.enums.ActionType;
import com.cts.fundtrack.common.models.enums.DisbursementStatus;
import com.cts.fundtrack.common.models.enums.EntityType;
import com.cts.fundtrack.common.models.enums.NotificationCategory;
import com.cts.fundtrack.common.models.enums.PaymentStatus;
import com.cts.fundtrack.disbursement.mapper.ModuleMapper;
import com.cts.fundtrack.disbursement.models.Disbursement;
import com.cts.fundtrack.disbursement.models.Payment;
import com.cts.fundtrack.disbursement.repository.DisbursementRepository;
import com.cts.fundtrack.disbursement.repository.PaymentRepository;
import com.cts.fundtrack.disbursement.util.EncryptionUtil;

import jakarta.servlet.http.HttpServletRequest;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

/**
 * Primary implementation of the {@link PaymentService} interface.
 * <p>
 * This service handles the actual execution layer of the disbursement lifecycle —
 * recording individual payment transactions, enforcing idempotency (no duplicate
 * settlements per installment), decrypting secure payment identifiers for record
 * retrieval, and providing full payment history for grant applications.
 * </p>
 * <p>
 * Payment IDs are never exposed in raw UUID form to external callers; all outbound
 * references use AES-encrypted identifiers generated by {@link EncryptionUtil}.
 * Audit events are emitted for all operations via the
 * {@link com.cts.fundtrack.common.aspect.Auditable} AOP annotation.
 * </p>
 */
@Slf4j
@RequiredArgsConstructor
@Service
public class PaymentServiceImpl implements PaymentService {

    private final PaymentRepository paymentRepo;
    private final DisbursementRepository disbursementRepo;
    private final ModuleMapper mapper;
    private final EncryptionUtil encryptionUtil;
    private final NotificationClient notificationClient;
    private final HttpServletRequest request;

    /**
     * Extracts the authenticated user's UUID from the {@code X-User-Id} header
     * injected by the API Gateway filter chain.
     *
     * @return the current user's {@link UUID}, or {@code null} if the header is absent
     */
    private UUID getCurrentUserId() {
        String userIdStr = request.getHeader("X-User-Id");
        return userIdStr != null ? UUID.fromString(userIdStr) : null;
    }

    @Transactional
    @Override
    @Auditable(action = ActionType.CREATE, entityName = EntityType.PAYMENT)
    public PaymentResponseDTO processPayment(PaymentRequestDTO dto) {
        log.info("Initiating financial settlement for Disbursement ID: {}", dto.getDisbursementId());

        Disbursement disbursement = disbursementRepo.findById(dto.getDisbursementId())
                .orElseThrow(() -> new DisbursementNotFoundException("Settlement Aborted: Target disbursement not found."));

        if (DisbursementStatus.PAID.equals(disbursement.getStatus())) {
            log.warn("Transaction Rejected: Disbursement {} is already settled.", dto.getDisbursementId());
            throw new DuplicateTransactionException("This installment has already been settled.");
        }

        if (DisbursementStatus.CANCELLED.equals(disbursement.getStatus())) {
            throw new InvalidProgramStateException("Settlement Denied: This installment was previously cancelled.");
        }

        Payment payment = Payment.builder()
                .disbursementId(disbursement.getDisbursementId())
                .amount(disbursement.getAmount())
                .method(dto.getMethod())
                .date(Instant.now())
                .status(PaymentStatus.SUCCESS)
                .build();

        Payment savedPayment = paymentRepo.save(payment);

        disbursement.setStatus(DisbursementStatus.PAID);
        disbursement.setActualDate(LocalDate.now());
        disbursementRepo.save(disbursement);

        log.info("Settlement Successful: Payment {} processed for amount {}",
                 savedPayment.getPaymentId(), disbursement.getAmount());

        // Notification: Confirmation to the currently logged-in Admin/Staff
        sendInternalNotification(getCurrentUserId(), null,
            "Payment Processed: You have successfully recorded a settlement of " + disbursement.getAmount() + " for Disbursement ID: " + disbursement.getDisbursementId(),
            NotificationCategory.DISBURSEMENT);

        return mapper.toPaymentResponseDTO(savedPayment);
    }

    @Override
    @Transactional(readOnly = true)
    @Auditable(action = ActionType.READ, entityName = EntityType.PAYMENT)
    public PaymentResponseDTO getPaymentByEncryptedId(String encryptedPaymentId) {
        log.debug("Accessing encrypted payment record reference.");
        UUID rawId;
        try {
            rawId = encryptionUtil.decrypt(encryptedPaymentId);
        } catch (Exception e) {
            log.warn("Security Alert: Invalid encrypted payment ID provided.");
            throw new PaymentNotFoundException("Invalid payment reference.");
        }

        Payment payment = paymentRepo.findById(rawId)
                .orElseThrow(() -> new PaymentNotFoundException("Payment record not found."));

        return mapper.toPaymentResponseDTO(payment);
    }

    @Override
    @Transactional(readOnly = true)
    @Auditable(action = ActionType.READ, entityName = EntityType.PAYMENT)
    public List<PaymentResponseDTO> getPaymentsByApplication(UUID applicationId) {
        log.debug("Retrieving payment history for Application ID: {}", applicationId);

        List<Disbursement> disbursements = disbursementRepo.findAllByApplicationId(applicationId);
        List<UUID> disbursementIds = disbursements.stream()
                .map(Disbursement::getDisbursementId)
                .collect(Collectors.toList());

        if (disbursementIds.isEmpty()) {
            return Collections.emptyList();
        }

        return paymentRepo.findAllByDisbursementIdIn(disbursementIds).stream()
                .map(mapper::toPaymentResponseDTO)
                .collect(Collectors.toList());
    }

    @Override
    @Auditable(action = ActionType.READ, entityName = EntityType.PAYMENT)
    public byte[] generatePaymentReceipt(String encryptedPaymentId) {
        log.info("Exporting financial receipt for Payment ID: {}", encryptedPaymentId);
        return new byte[0];
    }

    /**
     * Dispatches a transactional confirmation notification to the Finance Officer
     * after a payment is successfully processed.
     * <p>
     * Notification failures are caught and logged as non-critical errors so that they
     * never roll back the enclosing payment transaction.
     * </p>
     *
     * @param userId   the UUID of the user to notify (typically the processing officer)
     * @param appId    the UUID of the application providing context for the notification;
     *                 may be {@code null} for officer-only confirmations
     * @param message  the human-readable notification message body
     * @param category the {@link NotificationCategory} used to classify the alert in the UI
     */
    private void sendInternalNotification(UUID userId, UUID appId, String message, NotificationCategory category) {
        if (userId == null) {
            log.warn("Notification skipped: No authenticated user ID found.");
            return;
        }
        try {
            NotificationRequestDTO notification = NotificationRequestDTO.builder()
                    .userId(userId)
                    .applicationId(appId)
                    .message(message)
                    .category(category)
                    .build();
            notificationClient.sendNotification(notification);
            log.debug("System alert queued for user: {}", userId);
        } catch (Exception e) {
            log.error("Notification Communication Failure for user {}: {}", userId, e.getMessage());
        }
    }
}
