package com.cts.fundtrack.common.dto;

import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

import com.cts.fundtrack.common.models.enums.ProgramStatus;

import lombok.Data;

/**
 * Data Transfer Object representing the output/response for a Program.
 * <p>
 * This class is used to send program details back to the client. It includes 
 * read-only information generated by the system, such as the unique identifier 
 * and the current lifecycle status of the program.
 * </p>
 */
@Data
public class ProgramResponseDTO {

    /**
     * The unique system-generated identifier (UUID) for the program.
     */
    private UUID programId;

    /**
     * The name of the program.
     */
    private String name;

    /**
     * A detailed description of the program.
     */
    private String description;

    /**
     * The allocated budget for the program.
     */
    private Double budget;

    /**
     * The date the program is scheduled to start.
     */
    private LocalDate startDate;

    /**
     * The date the program is scheduled to conclude.
     */
    private LocalDate endDate;

    /**
     * The current operational state of the program (e.g., ACTIVE, INACTIVE, DRAFT).
     * Based on the {@link Status} enumeration.
     */
    private ProgramStatus status;

    /**
     * A list of {@link EligibilityRuleDTO} criteria associated with this program.
     */
    private List<EligibilityRuleDTO> eligibilityRules;

    /**
     * A list of {@link RequiredDocumentDTO} documents necessary for application.
     */
    private List<RequiredDocumentDTO> requiredDocuments;
}

