package com.cts.fundtrack.identity.model;


import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import com.cts.fundtrack.common.models.enums.LoginStatus;
import com.cts.fundtrack.common.models.enums.Role;

import java.time.Instant;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

/**
 * Core security entity representing a registered system user.
 *
 * <p>This class implements {@link UserDetails} to integrate directly with Spring
 * Security's authentication pipeline. It manages authentication credentials,
 * role-based access control (RBAC), and account lifecycle state.</p>
 *
 * <p>The entity is persisted in the {@code app_users} table with database-level
 * indexes on {@code email} and {@code phone} for efficient lookup during
 * authentication and duplicate-detection checks.</p>
 *
 * <p>Design notes:</p>
 * <ul>
 *   <li>The {@code email} field doubles as the Spring Security principal name
 *       (returned by {@link #getUsername()}).</li>
 *   <li>Passwords are stored as BCrypt hashes — never in plaintext.</li>
 *   <li>Account expiry, locking, and credential expiry are not currently
 *       enforced at the entity level; those methods return {@code true} unconditionally.
 *       Account enablement can be wired to {@link LoginStatus} in the future.</li>
 * </ul>
 *
 * @see UserDetails
 * @see Role
 * @see LoginStatus
 */
@Entity
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "app_users",
        indexes = {
                @Index(name = "idx_users_email", columnList = "email"),
                @Index(name = "idx_users_phone", columnList = "phone")
        })
public class User implements UserDetails {

    /**
     * Unique system-generated UUID identifier for the user.
     *
     * <p>Generated by the database using the UUID strategy; never updated after
     * creation. Used as the primary key and as the entity ID embedded in JWTs.</p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "user_id", updatable = false, nullable = false)
    private UUID userId;

    /**
     * The full legal name of the user, as provided during registration.
     */
    @Column(nullable = false, length = 120)
    private String name;

    /**
     * Unique email address used as the primary username for authentication.
     *
     * <p>Stored in lower-case and trimmed at the service layer to ensure
     * case-insensitive uniqueness.</p>
     */
    @Column(nullable = false, unique = true, length = 150)
    private String email;

    /**
     * Unique contact phone number associated with the account.
     *
     * <p>Optional at the database level but enforced as unique to prevent
     * duplicate registrations using the same phone number.</p>
     */
    @Column(length = 30, unique = true)
    private String phone;

    /**
     * BCrypt-encoded password string.
     *
     * <p>Never stored or returned as plaintext. Encoding and verification are
     * handled by the {@link org.springframework.security.crypto.password.PasswordEncoder}
     * bean configured in
     * {@link com.cts.fundtrack.identity.config.SecurityConfig}.</p>
     */
    @Column(nullable = false)
    private String password;

    /**
     * The primary authorization role assigned to the user (e.g., {@code ADMIN},
     * {@code APPLICANT}).
     *
     * <p>Stored as its enum name string. Mapped to a Spring Security
     * {@link GrantedAuthority} by {@link #getAuthorities()} with the
     * {@code ROLE_} prefix applied.</p>
     */
    @Enumerated(EnumType.STRING)
    private Role role;

    /**
     * UTC instant recording when this account was first created.
     *
     * <p>Populated automatically by Hibernate's {@link CreationTimestamp} and
     * never updated thereafter ({@code updatable = false}).</p>
     */
    @CreationTimestamp
    @Column(name = "createdAt", nullable = false, updatable = false)
    private Instant createdAt;

    /**
     * Current login state of the account (e.g., {@code LOGGED_IN}, {@code LOGGED_OUT}).
     *
     * <p>Updated by the authentication service on login and logout events.
     * Can be used in the future to drive {@link #isEnabled()} for account suspension.</p>
     */
    @Enumerated(EnumType.STRING)
    private LoginStatus status;

    /**
     * Maps the internal {@link Role} enum to the Spring Security
     * {@link GrantedAuthority} collection expected by the framework.
     *
     * <p>The role name is prefixed with {@code ROLE_} (e.g., {@code Role.ADMIN}
     * becomes {@code "ROLE_ADMIN"}) to satisfy Spring Security's standard
     * {@code hasRole()} / {@code hasAuthority()} conventions.</p>
     *
     * @return a single-element list containing the user's granted authority
     */
    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return List.of(
                new SimpleGrantedAuthority("ROLE_" + role.name())
        );
    }

    /**
     * Returns the email address as the principal name used by Spring Security.
     *
     * <p>This value is stored in the JWT subject claim and in the
     * {@link org.springframework.security.core.context.SecurityContext} during
     * an authenticated request.</p>
     *
     * @return the user's email address
     */
    @Override
    public String getUsername() {
        return email;
    }

    /**
     * Indicates whether the user's account has expired.
     *
     * <p>Account expiry is not currently enforced; always returns {@code true}.</p>
     *
     * @return {@code true} unconditionally
     */
    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    /**
     * Indicates whether the user's account is locked.
     *
     * <p>Account locking is not currently enforced; always returns {@code true}.</p>
     *
     * @return {@code true} unconditionally
     */
    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    /**
     * Indicates whether the user's credentials (password) have expired.
     *
     * <p>Credential expiry is not currently enforced; always returns {@code true}.</p>
     *
     * @return {@code true} unconditionally
     */
    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    /**
     * Indicates whether the user's account is enabled and active.
     *
     * <p>Currently always returns {@code true}. This can be linked to the
     * {@link LoginStatus} field in the future to support account suspension
     * or deactivation.</p>
     *
     * @return {@code true} unconditionally
     */
    @Override
    public boolean isEnabled() {
        return true;
    }
}
