package com.cts.fundtrack.identity.repository;

import com.cts.fundtrack.identity.model.AuditLog;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.UUID;

/**
 * Spring Data JPA repository for {@link AuditLog} entities.
 *
 * <p>Provides standard CRUD operations inherited from {@link JpaRepository},
 * including save, find-by-ID, find-all, and delete. The primary key type is
 * {@link UUID}, matching the {@code auditId} field generated by the database.</p>
 *
 * <p>This repository is used by:</p>
 * <ul>
 *   <li>{@link com.cts.fundtrack.identity.aspect.AuditAspect} — to persist
 *       audit entries triggered by the {@code @Auditable} AOP aspect within
 *       the Identity Service itself.</li>
 *   <li>{@link com.cts.fundtrack.identity.controller.AuditInternalController} — to
 *       persist audit entries forwarded from external microservices.</li>
 *   <li>{@link com.cts.fundtrack.identity.service.AuditServiceImpl} — to persist
 *       programmatically constructed audit records.</li>
 * </ul>
 *
 * @see AuditLog
 */
@Repository
public interface AuditRepository extends JpaRepository<AuditLog, UUID> {
    List<AuditLog> findByUser_UserId(UUID userId);
    List<AuditLog> findByAction(com.cts.fundtrack.common.models.enums.ActionType action);
    List<AuditLog> findByEntityId(UUID entityId);
}
 