package com.cts.fundtrack.identity.service;

import java.util.UUID;

import com.cts.fundtrack.common.dto.ForgotPasswordResponseDTO;
import com.cts.fundtrack.common.dto.LoginRequestDTO;
import com.cts.fundtrack.common.dto.LoginResponseDTO;
import com.cts.fundtrack.common.dto.LogoutRequestDTO;
import com.cts.fundtrack.common.dto.LogoutResponseDTO;
import com.cts.fundtrack.common.dto.RegisterRequestDTO;
import com.cts.fundtrack.common.dto.RegisterResponseDTO;

/**
 * Service interface defining the core authentication and account-management
 * operations for the FundTrack Identity Service.
 *
 * <p>Implementations are responsible for:</p>
 * <ul>
 *   <li>Validating and persisting new user registrations.</li>
 *   <li>Authenticating credentials and issuing JWT + refresh token pairs.</li>
 *   <li>Invalidating refresh tokens and updating session state on logout.</li>
 *   <li>Generating and validating one-time password-reset tokens.</li>
 * </ul>
 *
 * <p>The primary implementation is
 * {@link AuthServiceImpl}, which is annotated with {@code @Auditable} on each
 * method so that every successful operation is recorded in the audit log.</p>
 *
 * @see AuthServiceImpl
 */
public interface AuthService {

    /**
     * Registers a new user account after validating uniqueness of email and phone.
     *
     * @param request the registration payload containing name, email, phone,
     *                password, and desired role
     * @return a {@link RegisterResponseDTO} summarising the newly created user
     * @throws com.cts.fundtrack.common.exceptions.DuplicateResourceException if the
     *         email or phone number is already registered
     */
    RegisterResponseDTO register(RegisterRequestDTO request);

    /**
     * Authenticates a user's credentials and issues a JWT access token plus a
     * refresh token.
     *
     * @param request the login payload containing the user's email and plaintext
     *                password
     * @return a {@link LoginResponseDTO} containing both tokens and basic profile
     *         information
     * @throws com.cts.fundtrack.common.exceptions.UserNotFoundException if no user
     *         exists with the supplied email
     * @throws org.springframework.security.authentication.BadCredentialsException
     *         if the password does not match
     */
    LoginResponseDTO login(LoginRequestDTO request);

    /**
     * Logs out the user by invalidating their refresh token and updating their
     * login status to {@code LOGGED_OUT}.
     *
     * @param request the logout payload containing the user's email
     * @return a {@link LogoutResponseDTO} confirming the email and user UUID of
     *         the logged-out account
     * @throws com.cts.fundtrack.common.exceptions.UserNotFoundException if no user
     *         exists with the supplied email
     */
    LogoutResponseDTO logout(LogoutRequestDTO request);

    /**
     * Initiates the forgot-password flow by generating a one-time reset token and
     * returning a password-reset link.
     *
     * @param email the registered email address of the user requesting a password reset
     * @return a {@link ForgotPasswordResponseDTO} containing the user's UUID and
     *         the generated reset URL
     * @throws com.cts.fundtrack.common.exceptions.UserNotFoundException if no user
     *         exists with the supplied email
     */
    ForgotPasswordResponseDTO forgotPassword(String email);

    /**
     * Consumes a one-time reset token and updates the user's password.
     *
     * <p>The token is invalidated immediately after use and cannot be reused.
     * The new password is BCrypt-encoded before being persisted.</p>
     *
     * @param token       the one-time reset token previously generated by
     *                    {@link #forgotPassword(String)}
     * @param newPassword the desired new plaintext password; will be encoded before
     *                    storage
     * @return the {@link UUID} of the user whose password was reset; used by the
     *         {@code @Auditable} AOP aspect to record the audit entry
     * @throws com.cts.fundtrack.common.exceptions.InvalidTokenException if the token
     *         is not found or has already been consumed
     */
    UUID resetPassword(String token, String newPassword);
}
