package com.cts.notification_service.dto;

import com.cts.notification_service.model.enums.NotificationCategory;
import com.cts.notification_service.model.enums.NotificationStatus;
import lombok.*;
import java.time.Instant;
import java.util.UUID;


/**
 * Data Transfer Object for outgoing notification responses.
 * This class represents the final state of a notification after it has been
 * processed by the service layer and persisted in the database.
 * It is primarily used to populate the user's notification feed on the frontend.
 */
@Data
@Builder
public class NotificationResponseDTO {

    /**
     * The unique primary key (UUID) of the notification.
     * Use this ID for subsequent operations like marking the notification
     * as 'READ' or deleting it.
     */
    private UUID notificationId;


    private UUID userId;

    private UUID applicationId;

    /**
     * The final text content to be displayed to the user.
     * This may be a custom message or a string generated by the template engine.
     */
    private String message;

    /**
     * The current viewing status of the notification (e.g., 'READ', 'UNREAD').
     * Determines how the notification is styled or filtered in the user interface.
     */
    private NotificationStatus status;

    /**
     * The timestamp of when the notification was generated.
     * Useful for sorting the notification list by the most recent alerts.
     */
    private Instant createdDate;

    /**
     * The classification of the notification (e.g., 'APPROVAL', 'WELCOME').
     * Can be used on the frontend to display specific icons or group
     * notifications by type.
     */
    private NotificationCategory category;
}



