# Server Configuration
server.port=8081
spring.application.name=fundtrack-api-gateway

# Gateway Discovery Settings (Keep these!)
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Security Properties
security.jwt.secret=mysecretmysecretmysecretmysecret

# Eureka Discovery Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

# Debugging (Keep these to see the Java routes load)
logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.http.server.reactive=DEBUG
logging.level.org.springframework.cloud.loadbalancer=DEBUG